### ISSUE TITLE
javax.management.InstanceNotFoundException with Wildfly 9

### ISSUE THREAD

**Issue by kavoori** [wildfly-extras/jmx-console#1]
Hello,

Thank you for this repository and I have used the jmx-console.war from this project successfully with Wildfly 8. I have looked a lot for a good port of the JMX console for AS7 and Wildfly 8 and I can say that your repository is the best one I have found so far. 

However, I recently upgraded to Wildfly 9 and and when I deployed the war, the page throws the following error.

```
20:12:06,935 ERROR [io.undertow.request] (default task-2) UT005023: Exception handling request to /jmx-console/filterView.jsp: javax.servlet.ServletException: javax.management.InstanceNotFoundException: jboss.as.expr:core-service=management,service=management-operations,active-operation=27688171
    at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:848)
    at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:777)
    at org.apache.jsp.filterView_jsp._jspService(filterView_jsp.java:107)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:69)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:366)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:326)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:259)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)
    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
    at io.undertow.jsp.JspFileHandler.handleRequest(JspFileHandler.java:32)
    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
    at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
    at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
    at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:51)
    at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
    at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
    at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:56)
    at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
    at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:72)
    at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
    at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:261)
    at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:80)
    at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:172)
    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:774)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: javax.management.InstanceNotFoundException: jboss.as.expr:core-service=management,service=management-operations,active-operation=27688171
    at org.jboss.as.jmx.PluggableMBeanServerImpl.findDelegate(PluggableMBeanServerImpl.java:1154)
    at org.jboss.as.jmx.PluggableMBeanServerImpl.getMBeanInfo(PluggableMBeanServerImpl.java:594)
    at org.jboss.as.jmx.PluggableMBeanServerImpl.getMBeanInfo(PluggableMBeanServerImpl.java:586)
    at org.wildfly.extras.jmxconsole.control.Server.getDomainData(Server.java:82)
    at org.apache.jsp.filterView_jsp._jspService(filterView_jsp.java:85)
    ... 37 more
```

I am not entirely familiar with the internals of Jboss AS subsystems, but I was able to get around the above error by simply catching the exception and continuing as follows:

``` java
public static Iterator getDomainData(String filter) throws JMException {
        MBeanServer server = getMBeanServer();
        TreeMap domainData = new TreeMap();
        if (server != null) {
            ObjectName filterName = null;
            if (filter != null) filterName = new ObjectName(filter);
            Set objectNames = server.queryNames(filterName, null);
            Iterator objectNamesIter = objectNames.iterator();
            while (objectNamesIter.hasNext()) {
                ObjectName name = (ObjectName) objectNamesIter.next();
                if (omittedDomains.contains(name.getDomain())) {
                    continue;
                }
                MBeanInfo info;
                try{
                     info = server.getMBeanInfo(name);
                }catch(javax.management.InstanceNotFoundException e){
                    continue;
                }

                String domainName = name.getDomain();
                MBeanData mbeanData = new MBeanData(name, info);
                DomainData data = (DomainData) domainData.get(domainName);
                if (data == null) {
                    data = new DomainData(domainName);
                    domainData.put(domainName, data);
                }
                data.addData(mbeanData);
            }
        }
        Iterator domainDataIter = domainData.values().iterator();
        return domainDataIter;
    }
```

After this, and also upgrading to `<wildfly.version>8.2.1.Final</wildfly.version>` in the `pom.xml`, I was able to deploy the war successfully to Wildfly 9. I am wondering if there is a better way to solve the above error. If you wish, I can submit a pull request with the above changes.

Thanks again for the good work!

**Comment by sentinelt** [comment]
Just in case you have not found it yet, there is a newer JMX console available at http://hawt.io/plugins/jmx/.

**Comment by kavoori** [comment]
Thanks! I will check it out.

**Comment by GrahamJohnson** [comment]
I am seeing the same issue (in the left frame) along with the less frequent similar error below (in the right frame).

I can confirm this workaround works (thanks to @kavoori for documenting it).

Also, for what it's worth, if you reload either frame that gets an error, it then loads without error and the JMX console is usable after that (in case anyone is stuck having to use an unfixed version).

```
UT005023: Exception handling request to /jmx-console/HtmlAdaptor: javax.servlet.ServletException: Failed to get MBeans
    at org.wildfly.extras.jmxconsole.html.HtmlAdaptorServlet.displayMBeans(HtmlAdaptorServlet.java:175) [classes:]
[...]
Caused by: java.security.PrivilegedActionException: javax.management.InstanceNotFoundException: jboss.as.expr:core-service=management,service=management-operations,active-operation=1777334426
    at java.security.AccessController.doPrivileged(Native Method) [rt.jar:1.8.0_45]
    at org.wildfly.extras.jmxconsole.html.HtmlAdaptorServlet.getDomainData(HtmlAdaptorServlet.java:308) [classes:]
    at org.wildfly.extras.jmxconsole.html.HtmlAdaptorServlet.displayMBeans(HtmlAdaptorServlet.java:169) [classes:]
    ... 31 more
Caused by: javax.management.InstanceNotFoundException: jboss.as.expr:core-service=management,service=management-operations,active-operation=1777334426
    at org.jboss.as.jmx.PluggableMBeanServerImpl.findDelegate(PluggableMBeanServerImpl.java:1154)
    at org.jboss.as.jmx.PluggableMBeanServerImpl.getMBeanInfo(PluggableMBeanServerImpl.java:594)
    at org.jboss.as.jmx.PluggableMBeanServerImpl.getMBeanInfo(PluggableMBeanServerImpl.java:586)
    at org.wildfly.extras.jmxconsole.control.Server.getDomainData(Server.java:82) [classes:]
    at org.wildfly.extras.jmxconsole.html.HtmlAdaptorServlet$2.run(HtmlAdaptorServlet.java:311) [classes:]
    at org.wildfly.extras.jmxconsole.html.HtmlAdaptorServlet$2.run(HtmlAdaptorServlet.java:308) [classes:]
    ... 34 more
```
